import { Info } from "lucide-react";
import type { AISummary } from "@/lib/types";

type AISummaryCardProps = {
  aiSummary: AISummary | null;
};

export function AISummaryCard({ aiSummary }: AISummaryCardProps) {
  if (!aiSummary || aiSummary.summary.trim().length === 0) {
    return null;
  }

  return (
    <section className="glass-card rounded-[2rem] p-6 shadow-soft">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="card-title">AI-Powered Insights</p>
          <h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">
            Gemini-generated summary
          </h2>
        </div>
        <div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">
          <Info className="h-3.5 w-3.5" />
          Generated by Gemini
        </div>
      </div>

      <p className="mt-4 text-sm leading-7 text-slate-700">
        {aiSummary.summary}
      </p>

      {aiSummary.highlights.length > 0 ? (
        <ul className="mt-5 space-y-3 text-sm text-slate-700">
          {aiSummary.highlights.map((highlight) => (
            <li
              key={highlight}
              className="flex gap-3 rounded-2xl bg-slate-50 px-4 py-3"
            >
              <span className="mt-2 h-2 w-2 rounded-full bg-blue-500" />
              <span>{highlight}</span>
            </li>
          ))}
        </ul>
      ) : null}

      <p className="mt-4 text-xs uppercase tracking-[0.2em] text-slate-500">
        Updated {new Date(aiSummary.updated_at).toLocaleString()}
      </p>
    </section>
  );
}
